title: Yii.Rocks
description: The missing pieces for your Yii 3 projects.
url: "https://www.yii.rocks"
logo: /assets/images/logo-180.png
author: Mr. 42

plugins:
    - jekyll-seo-tag
    - jekyll-sitemap

sass:
    style: compressed